### PR TITLE
Added No Advertising rule

### PR DESCRIPTION
**Pull request by PYRiTEmonark**
Points of intrest:
> Should the clarifications included with the rule be part of the amendment
Specifically: "Posting something cool you made is encouraged, soliciting people to work on it is not"

> Is this rule to restrictive?
See above, don't want to stop people from sharing a cool thing that they made, but don't want people just straight up advertising

### CODE REVIEW

**Comment by sersorrel** [comment]
+1 on including the clarifications, this feels somewhat vague otherwise

i remain not entirely happy with the wording (e.g. is posting something cool someone else made cool ("hacksoc bans twitter links from their slack")? how much of committee has to ok it first?), but it's passed a committee vote, so

**Comment by sersorrel** [comment]
per discord conversation, suggested wording:

> Please don't enter HackSoc social spaces in order to advertise

**Comment by markspolakovs** [comment]
IMO that’s a good wording (“please don’t enter in order to advertise”) captures the spirit well. Do we want to have something about “if you wanna advertise something check with committee first” or do we think that doesn’t go in the constitution?

**Comment by PYRiTEmonark** [comment]
Changing the procedure for approved advertising is unlikely however I don't think thats something we want to have the entire comittee vote on to have to change. That information should be somewere though.

**Review by markspolakovs — APPROVED** [review]
Voted on at committee meeting: 9 yes 0 no 0 abstentions

**Pull request merged**
